# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

check_lyapunov <- function(Phi_c, Phi_f, phi_r, seed, D = 250L, m = 100L) {
    .Call(`_tvvar_check_lyapunov`, Phi_c, Phi_f, phi_r, seed, D, m)
}

my_loop_main <- function(ytilde, Z, startP, cov, startH, momega, pphi, A, B, Q) {
    .Call(`_tvvar_my_loop_main`, ytilde, Z, startP, cov, startH, momega, pphi, A, B, Q)
}

create_Y_minus1 <- function(Y, lag_order, T_fin, dim_VAR) {
    .Call(`_tvvar_create_Y_minus1`, Y, lag_order, T_fin, dim_VAR)
}

create_Z <- function(Y_minus1, Phi_f, Q_here, T_fin, dim_VAR, number_factors, lag_order) {
    .Call(`_tvvar_create_Z`, Y_minus1, Phi_f, Q_here, T_fin, dim_VAR, number_factors, lag_order)
}

